/*
 * Copyright (c) 2024 Arm Limited.
 *
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * @file
 *
 * Convert stream data to string.
 */

#pragma once

#include <device/hwcnt/print.hpp>
#include <device/ioctl/kinstr_prfcnt/print.hpp>

#include <sstream>

namespace hwcpipe {
namespace device {
namespace hwcnt {
namespace detail {

/**
 * Template function to convert stream data to string for logging.
 *
 * Interface classes of hwcpipe2 are autogenerated along with a stream
 * overloading to output class data through stdout, but since the logger
 * uses printf format we need to capture these data in string format.
 *
 * @param[in] obj   Object to get string data for.
 * @return std::string.
 */
template <typename T>
inline std::string to_str(T obj) {
    std::stringstream ss;
    ss << obj;
    return ss.str();
}

} // namespace detail
} // namespace hwcnt
} // namespace device
} // namespace hwcpipe
