/*
 * Copyright (c) 2023-2026 Arm Limited.
 *
 * SPDX-License-Identifier: MIT
 */

#include "hwcpipe/counter_metadata.hpp"

namespace hwcpipe {
namespace database {

    constexpr std::array<counter_metadata, 548> all_counter_metadata {
        counter_metadata {"Arithmetic unit issue cycles", "cycles"},
        counter_metadata {"Average ALU cycles per thread", "cycles"},
        counter_metadata {"Arithmetic unit utilization", "percent"},
        counter_metadata {"Attribute unit instructions", "instructions"},
        counter_metadata {"Programmable core active cycles", "cycles"},
        counter_metadata {"Programmable core utilization", "percent"},
        counter_metadata {"Diverged instructions", "instructions"},
        counter_metadata {"Warp divergence percentage", "percent"},
        counter_metadata {"Arithmetic instruction issue cycles", "instructions"},
        counter_metadata {"Instruction issue starvation cycles", "cycles"},
        counter_metadata {"Output external read transactions", "transactions"},
        counter_metadata {"Output external read beats", "beats"},
        counter_metadata {"Output external read bytes", "bytes"},
        counter_metadata {"Output external read latency 0-127 cycles", "beats"},
        counter_metadata {"Output external read latency 128-191 cycles", "beats"},
        counter_metadata {"Output external read latency 192-255 cycles", "beats"},
        counter_metadata {"Output external read latency 256-319 cycles", "beats"},
        counter_metadata {"Output external read latency 320-383 cycles", "beats"},
        counter_metadata {"Output external read latency 384+ cycles", "beats"},
        counter_metadata {"Output external ReadNoSnoop transactions", "transactions"},
        counter_metadata {"Output external outstanding reads 0-25%", "transactions"},
        counter_metadata {"Output external outstanding reads 25-50%", "transactions"},
        counter_metadata {"Output external outstanding reads 50-75%", "transactions"},
        counter_metadata {"Output external outstanding reads 75-100%", "transactions"},
        counter_metadata {"Output external read stall cycles", "cycles"},
        counter_metadata {"Output external read stall percentage", "percent"},
        counter_metadata {"Output external ReadUnique transactions", "transactions"},
        counter_metadata {"Output external write transactions", "transactions"},
        counter_metadata {"Output external write beats", "beats"},
        counter_metadata {"Output external write bytes", "bytes"},
        counter_metadata {"Output external WriteNoSnoopFull transactions", "transactions"},
        counter_metadata {"Output external WriteNoSnoopPartial transactions", "transactions"},
        counter_metadata {"Output external outstanding writes 0-25%", "transactions"},
        counter_metadata {"Output external outstanding writes 25-50%", "transactions"},
        counter_metadata {"Output external outstanding writes 50-75%", "transactions"},
        counter_metadata {"Output external outstanding writes 75-100%", "transactions"},
        counter_metadata {"Output external WriteSnoopFull transactions", "transactions"},
        counter_metadata {"Output external WriteSnoopPartial transactions", "transactions"},
        counter_metadata {"Output external write stall cycles", "cycles"},
        counter_metadata {"Output external write stall percentage", "percent"},
        counter_metadata {"Shader core fragment active cycles", "cycles"},
        counter_metadata {"Early ZS killed quads", "quads"},
        counter_metadata {"Early ZS killed quad percentage", "percent"},
        counter_metadata {"Early ZS tested quads", "quads"},
        counter_metadata {"Early ZS tested quad percentage", "percent"},
        counter_metadata {"Early ZS updated quads", "quads"},
        counter_metadata {"Early ZS updated quad percentage", "percent"},
        counter_metadata {"FPK HSR killed quads", "quads"},
        counter_metadata {"FPK HSR killed quad percentage", "percent"},
        counter_metadata {"Late ZS killed quads", "quads"},
        counter_metadata {"Late ZS killed quad percentage", "percent"},
        counter_metadata {"Late ZS tested quads", "quads"},
        counter_metadata {"Late ZS tested quad percentage", "percent"},
        counter_metadata {"Occluding quads", "quads"},
        counter_metadata {"Occluding quad percentage", "percent"},
        counter_metadata {"Fragments per pixel", "threads"},
        counter_metadata {"Partial fragment warps", "warps"},
        counter_metadata {"Partial coverage percentage", "percent"},
        counter_metadata {"Loaded fragment primitives", "primitives"},
        counter_metadata {"Fragment queue active cycles", "cycles"},
        counter_metadata {"Fragment jobs", "jobs"},
        counter_metadata {"Fragment tasks", "tasks"},
        counter_metadata {"Fragment queue utilization", "percent"},
        counter_metadata {"Fragment queue job dependency wait cycles", "cycles"},
        counter_metadata {"Fragment queue job finish wait cycles", "cycles"},
        counter_metadata {"Fragment queue cache flush wait cycles", "cycles"},
        counter_metadata {"Fragment queue job issue wait cycles", "cycles"},
        counter_metadata {"Fragment queue job descriptor read wait cycles", "cycles"},
        counter_metadata {"Rasterized primitives", "primitives"},
        counter_metadata {"Rasterized fine quads", "quads"},
        counter_metadata {"Shaded coarse quads", "quads"},
        counter_metadata {"Fragment shading staging buffer active cycles", "cycles"},
        counter_metadata {"Fragment shading staging buffer utilization", "percent"},
        counter_metadata {"Fragment threads", "threads"},
        counter_metadata {"Average cycles per fragment thread", "cycles"},
        counter_metadata {"Tiles", "tiles"},
        counter_metadata {"Killed unchanged tiles", "tiles"},
        counter_metadata {"Unchanged tile kill percentage", "percent"},
        counter_metadata {"Non-occluding quads", "quads"},
        counter_metadata {"Shader core fragment utilization", "percent"},
        counter_metadata {"Fragment warps", "warps"},
        counter_metadata {"GPU active cycles", "cycles"},
        counter_metadata {"Average cycles per pixel", "cycles"},
        counter_metadata {"GPU interrupt pending cycles", "cycles"},
        counter_metadata {"Interrupt pending utilization", "percent"},
        counter_metadata {"Pixels", "pixels"},
        counter_metadata {"Visible back-facing primitives", "primitives"},
        counter_metadata {"Facing or XY plane test culled primitives", "primitives"},
        counter_metadata {"Facing or XY plane test cull percentage", "percent"},
        counter_metadata {"Visible front-facing primitives", "primitives"},
        counter_metadata {"Line primitives", "primitives"},
        counter_metadata {"Point primitives", "primitives"},
        counter_metadata {"Sample test culled primitives", "primitives"},
        counter_metadata {"Sample test cull percentage", "percent"},
        counter_metadata {"Culled primitives", "primitives"},
        counter_metadata {"Input primitives", "primitives"},
        counter_metadata {"Triangle primitives", "primitives"},
        counter_metadata {"Visible primitives", "primitives"},
        counter_metadata {"Visible primitive percentage", "percent"},
        counter_metadata {"Z plane test culled primitives", "primitives"},
        counter_metadata {"Z plane test cull percentage", "percent"},
        counter_metadata {"L2 cache flush requests", "requests"},
        counter_metadata {"Input external snoop transactions", "transactions"},
        counter_metadata {"Input external snoop stall cycles", "cycles"},
        counter_metadata {"Output internal read requests", "requests"},
        counter_metadata {"Output internal read stall cycles", "cycles"},
        counter_metadata {"Output internal write requests", "requests"},
        counter_metadata {"L2 cache lookup requests", "requests"},
        counter_metadata {"Input internal read requests", "requests"},
        counter_metadata {"L2 cache read hit rate", "percent"},
        counter_metadata {"L2 cache read lookups", "requests"},
        counter_metadata {"L2 cache read miss rate", "percent"},
        counter_metadata {"Input internal read stall cycles", "cycles"},
        counter_metadata {"Input internal snoop requests", "requests"},
        counter_metadata {"Input external snoop lookup requests", "requests"},
        counter_metadata {"Input internal snoop stall cycles", "cycles"},
        counter_metadata {"Input internal write requests", "requests"},
        counter_metadata {"L2 cache write hit rate", "percent"},
        counter_metadata {"L2 cache write lookups", "requests"},
        counter_metadata {"L2 cache write miss rate", "percent"},
        counter_metadata {"Input internal write stall cycles", "cycles"},
        counter_metadata {"Load/store unit atomic issues", "cycles"},
        counter_metadata {"Load/store unit full read issues", "cycles"},
        counter_metadata {"Load/store unit full write issues", "cycles"},
        counter_metadata {"Load/store unit issue cycles", "cycles"},
        counter_metadata {"Load/store unit partial read issues", "cycles"},
        counter_metadata {"Load/store unit partial write issues", "cycles"},
        counter_metadata {"Load/store unit read issues", "cycles"},
        counter_metadata {"Average load/store unit cycles per thread", "cycles"},
        counter_metadata {"Load/store unit utilization", "percent"},
        counter_metadata {"Load/store unit write issues", "cycles"},
        counter_metadata {"MMU level 2 lookup TLB hits", "requests"},
        counter_metadata {"MMU level 2 lookup TLB hit rate", "percent"},
        counter_metadata {"MMU level 2 lookup TLB misses", "requests"},
        counter_metadata {"MMU level 3 lookup TLB hits", "requests"},
        counter_metadata {"MMU level 3 lookup TLB hit rate", "percent"},
        counter_metadata {"MMU level 3 lookup TLB misses", "requests"},
        counter_metadata {"MMU lookup requests", "requests"},
        counter_metadata {"Shader core non-fragment active cycles", "cycles"},
        counter_metadata {"Non-fragment queue active cycles", "cycles"},
        counter_metadata {"Non-fragment jobs", "jobs"},
        counter_metadata {"Non-fragment tasks", "tasks"},
        counter_metadata {"Non-fragment queue utilization", "percent"},
        counter_metadata {"Non-fragment queue job dependency wait cycles", "cycles"},
        counter_metadata {"Non-fragment queue job finish wait cycles", "cycles"},
        counter_metadata {"Non-fragment queue cache flush wait cycles", "cycles"},
        counter_metadata {"Non-fragment queue job issue wait cycles", "cycles"},
        counter_metadata {"Non-fragment queue job descriptor read wait cycles", "cycles"},
        counter_metadata {"Non-fragment core tasks", "tasks"},
        counter_metadata {"Non-fragment threads", "threads"},
        counter_metadata {"Average cycles per non-fragment thread", "cycles"},
        counter_metadata {"Shader core non-fragment utilization", "percent"},
        counter_metadata {"Non-fragment warps", "warps"},
        counter_metadata {"Reserved active cycles", "cycles"},
        counter_metadata {"Reserved queue jobs", "jobs"},
        counter_metadata {"Reserved queue tasks", "tasks"},
        counter_metadata {"Reserved queue job dependency wait cycles", "cycles"},
        counter_metadata {"Reserved queue job finish wait cycles", "cycles"},
        counter_metadata {"Reserved queue cache flush wait cycles", "cycles"},
        counter_metadata {"Reserved queue job issue wait cycles", "cycles"},
        counter_metadata {"Reserved queue job descriptor read wait cycles", "cycles"},
        counter_metadata {"Fragment front-end read beats from external memory", "beats"},
        counter_metadata {"Fragment front-end read bytes from external memory", "bytes"},
        counter_metadata {"Fragment front-end read beats from L2 cache", "beats"},
        counter_metadata {"Fragment front-end read bytes from L2 cache", "bytes"},
        counter_metadata {"Load/store unit read beats from external memory", "beats"},
        counter_metadata {"Load/store unit read bytes from external memory", "bytes"},
        counter_metadata {"Load/store unit bytes read from external memory per access cycle", "bytes"},
        counter_metadata {"Load/store unit read beats from L2 cache", "beats"},
        counter_metadata {"Load/store unit read bytes from L2 cache", "bytes"},
        counter_metadata {"Load/store unit bytes read from L2 per access cycle", "bytes"},
        counter_metadata {"Load/store unit other write beats to L2 memory system", "beats"},
        counter_metadata {"Load/store unit write-back write beats to L2 memory system", "beats"},
        counter_metadata {"Load/store unit write beats to L2 memory system", "beats"},
        counter_metadata {"Load/store unit write bytes to L2 memory system", "bytes"},
        counter_metadata {"Load/store unit bytes written to L2 per access cycle", "bytes"},
        counter_metadata {"Other shader core read beats from L2 cache", "beats"},
        counter_metadata {"Other shader core read bytes from L2 cache", "bytes"},
        counter_metadata {"Texture unit read beats from external memory", "beats"},
        counter_metadata {"Texture unit read bytes from external memory", "bytes"},
        counter_metadata {"Texture unit bytes read from external memory per texture cycle", "bytes"},
        counter_metadata {"Texture unit read beats from L2 cache", "beats"},
        counter_metadata {"Texture unit read bytes from L2 cache", "bytes"},
        counter_metadata {"Texture unit bytes read from L2 per texture cycle", "bytes"},
        counter_metadata {"Tile unit bytes written to L2 memory system per pixel", "bytes"},
        counter_metadata {"Tile unit write beats to L2 memory system", "beats"},
        counter_metadata {"Tile unit write bytes to L2 memory system", "bytes"},
        counter_metadata {"Texture filtering cycles per instruction", "cycles"},
        counter_metadata {"Texture unit compressed line fetch requests", "issues"},
        counter_metadata {"Texture unit compressed line fetch request percentage", "percent"},
        counter_metadata {"Texture unit line fetch requests", "issues"},
        counter_metadata {"Texture unit data cache lookup requests", "cycles"},
        counter_metadata {"Texture unit cache lookup utilization", "percent"},
        counter_metadata {"Texture unit filtering cycles", "cycles"},
        counter_metadata {"Texture unit filtering utilization", "percent"},
        counter_metadata {"Texture unit issue cycles", "cycles"},
        counter_metadata {"Texture unit samples using mipmapping percentage", "percent"},
        counter_metadata {"Texture unit quad issues", "issues"},
        counter_metadata {"Texture unit quad descriptor misses", "requests"},
        counter_metadata {"Texture unit mipmapped texture quad issues", "issues"},
        counter_metadata {"Trilinear unit filtered texture quad issues", "issues"},
        counter_metadata {"Texture unit quads", "quads"},
        counter_metadata {"Texture samples", "requests"},
        counter_metadata {"Average texture unit cycles per thread", "cycles"},
        counter_metadata {"Texture unit samples using trilinear filter percentage", "percent"},
        counter_metadata {"Texture unit utilization", "percent"},
        counter_metadata {"Tiler active cycles", "cycles"},
        counter_metadata {"Tiler position cache hits", "requests"},
        counter_metadata {"Tiler position cache hit rate", "percent"},
        counter_metadata {"Tiler position cache misses", "requests"},
        counter_metadata {"Tiler position FIFO full cycles", "cycles"},
        counter_metadata {"Tiler position shading stall cycles", "cycles"},
        counter_metadata {"Tiler position shading requests", "requests"},
        counter_metadata {"Position shader thread invocations", "threads"},
        counter_metadata {"Position shader threads per input primitive", "threads"},
        counter_metadata {"Tiler position shading outstanding cycles", "cycles"},
        counter_metadata {"Tiler read beats from the L2 memory system", "beats"},
        counter_metadata {"Tiler read bytes from the L2 memory system", "bytes"},
        counter_metadata {"Tiler utilization", "percent"},
        counter_metadata {"Tiler varying cache hits", "requests"},
        counter_metadata {"Tiler varying cache hit rate", "percent"},
        counter_metadata {"Tiler varying cache misses", "requests"},
        counter_metadata {"Tiler varying shading stall cycles", "cycles"},
        counter_metadata {"Tiler varying shading requests", "requests"},
        counter_metadata {"Varying shader thread invocations", "threads"},
        counter_metadata {"Varying shader threads per input primitive", "threads"},
        counter_metadata {"Tiler write beats to L2 memory system", "beats"},
        counter_metadata {"Tiler write bytes to L2 memory system", "bytes"},
        counter_metadata {"Varying unit 16-bit interpolation issue cycles", "cycles"},
        counter_metadata {"Varying unit 16-bit interpolation slot issues", "issues"},
        counter_metadata {"Varying unit 32-bit interpolation issue cycles", "cycles"},
        counter_metadata {"Varying unit 32-bit interpolation slot issues", "issues"},
        counter_metadata {"Varying unit instructions", "requests"},
        counter_metadata {"Varying unit issue cycles", "cycles"},
        counter_metadata {"Average varying unit cycles per thread", "cycles"},
        counter_metadata {"Varying unit utilization", "percent"},
        counter_metadata {"Warps using more than 32 registers", "warps"},
        counter_metadata {"All registers warp percentage", "percent"},
        counter_metadata {"Full warps", "warps"},
        counter_metadata {"Full warp percentage", "percent"},
        counter_metadata {"Other shader core write beats to L2 memory system", "beats"},
        counter_metadata {"Other shader core unit write bytes to L2 memory system", "bytes"},
        counter_metadata {"Texture unit 3D texture instructions", "requests"},
        counter_metadata {"Texture unit samples using 3D texture percentage", "percent"},
        counter_metadata {"Texture unit compressed texture instructions", "requests"},
        counter_metadata {"Texture unit samples using compressed texture percentage", "percent"},
        counter_metadata {"Texture unit filtering coordinate stall cycles", "cycles"},
        counter_metadata {"Texture unit line fill stall cycles", "cycles"},
        counter_metadata {"Texture unit instructions", "requests"},
        counter_metadata {"Texture unit mipmapped texture instructions", "requests"},
        counter_metadata {"Texture unit filtering partial data stall cycles", "cycles"},
        counter_metadata {"Texture unit trilinear filtered texture instructions", "requests"},
        counter_metadata {"Arithmetic instructions", "instructions"},
        counter_metadata {"Arithmetic CVT pipe instructions", "instructions"},
        counter_metadata {"CVT pipe utilization", "percent"},
        counter_metadata {"Arithmetic FMA pipe instructions", "instructions"},
        counter_metadata {"FMA pipe utilization", "percent"},
        counter_metadata {"Shader core instruction cache misses", "requests"},
        counter_metadata {"Arithmetic SFU pipe instructions", "instructions"},
        counter_metadata {"SFU pipe utilization", "percent"},
        counter_metadata {"Blend shader instructions", "instructions"},
        counter_metadata {"Shader blend percentage", "percent"},
        counter_metadata {"Partial rasterized fine quads", "quads"},
        counter_metadata {"Partial coverage percentage", "percent"},
        counter_metadata {"Texture unit data fetch stall cycles", "cycles"},
        counter_metadata {"Texture unit descriptor stall cycles", "cycles"},
        counter_metadata {"Texture unit full speed filtering percentage", "percent"},
        counter_metadata {"Texture unit filtering stall cycles", "cycles"},
        counter_metadata {"Texture unit filtering cycles using full bilinear", "cycles"},
        counter_metadata {"Texture unit filtering cycles using full trilinear", "cycles"},
        counter_metadata {"Texture unit message read beats", "beats"},
        counter_metadata {"Texture unit input bus utilization", "percent"},
        counter_metadata {"Texture unit message write beats", "beats"},
        counter_metadata {"Texture unit output bus utilization", "percent"},
        counter_metadata {"Texture unit messages", "issues"},
        counter_metadata {"Tiler port 0 write beats to L2 memory system", "beats"},
        counter_metadata {"Tiler port 1 write beats to L2 memory system", "beats"},
        counter_metadata {"Any shader core workload active cycles", "cycles"},
        counter_metadata {"Shader core clock ratio", "percent"},
        counter_metadata {"Command stream 0 wait stall cycles", "cycles"},
        counter_metadata {"Command stream 1 wait stall cycles", "cycles"},
        counter_metadata {"Command stream 2 wait stall cycles", "cycles"},
        counter_metadata {"Command stream 3 wait stall cycles", "cycles"},
        counter_metadata {"Command execution unit active cycles", "cycles"},
        counter_metadata {"Command execution unit utilization", "percent"},
        counter_metadata {"Command stream 0 active cycles", "cycles"},
        counter_metadata {"Command stream 1 active cycles", "cycles"},
        counter_metadata {"Command stream 2 active cycles", "cycles"},
        counter_metadata {"Command stream 3 active cycles", "cycles"},
        counter_metadata {"Command load/store unit active cycles", "cycles"},
        counter_metadata {"Command load/store unit utilization", "percent"},
        counter_metadata {"Microcontroller active cycles", "cycles"},
        counter_metadata {"Microcontroller utilization", "percent"},
        counter_metadata {"Compute queue active cycles", "cycles"},
        counter_metadata {"Compute queue endpoint stall cycles", "cycles"},
        counter_metadata {"Compute queue endpoint drain stall cycles", "cycles"},
        counter_metadata {"Compute queue interrupt pending cycles", "cycles"},
        counter_metadata {"Compute jobs", "jobs"},
        counter_metadata {"Compute tasks", "tasks"},
        counter_metadata {"Compute queue utilization", "percent"},
        counter_metadata {"Compute work queued cycles", "cycles"},
        counter_metadata {"Fragment queue endpoint stall cycles", "cycles"},
        counter_metadata {"Fragment queue interrupt pending cycles", "cycles"},
        counter_metadata {"Fragment work queued cycles", "cycles"},
        counter_metadata {"Any queue active cycles", "cycles"},
        counter_metadata {"GPU interrupts", "interrupts"},
        counter_metadata {"Input internal clean unique requests", "requests"},
        counter_metadata {"Input internal evict requests", "requests"},
        counter_metadata {"L2 cache flush cycles", "cycles"},
        counter_metadata {"MMU flush requests", "requests"},
        counter_metadata {"Vertex queue active cycles", "cycles"},
        counter_metadata {"Vertex queue endpoint stall cycles", "cycles"},
        counter_metadata {"Vertex queue endpoint drain stall cycles", "cycles"},
        counter_metadata {"Vertex queue interrupt pending cycles", "cycles"},
        counter_metadata {"Vertex jobs", "jobs"},
        counter_metadata {"Vertex tasks", "tasks"},
        counter_metadata {"Vertex queue utilization", "percent"},
        counter_metadata {"Vertex work queued cycles", "cycles"},
        counter_metadata {"Fragment warp occupancy", "percent"},
        counter_metadata {"Narrow arithmetic instructions", "instructions"},
        counter_metadata {"Narrow arithmetic percentage", "percent"},
        counter_metadata {"Rasterized coarse quads", "quads"},
        counter_metadata {"Fragment shading rate", "percent"},
        counter_metadata {"GPU active raw cycles", "cycles"},
        counter_metadata {"Facing test culled primitives", "primitives"},
        counter_metadata {"Facing test cull percentage", "percent"},
        counter_metadata {"Frustum test culled primitives", "primitives"},
        counter_metadata {"Frustum test cull percentage", "percent"},
        counter_metadata {"Ray tracing box tests", "boxes"},
        counter_metadata {"Ray tracing box nodes with 1-4 rays", "nodes"},
        counter_metadata {"Ray tracing box nodes with 13-16 rays", "nodes"},
        counter_metadata {"Ray tracing box nodes with 5-8 rays", "nodes"},
        counter_metadata {"Ray tracing box nodes with 9-12 rays", "nodes"},
        counter_metadata {"Ray tracing box tester issue cycles", "cycles"},
        counter_metadata {"Ray tracing first hit terminations", "rays"},
        counter_metadata {"Ray tracing unit issue cycles", "cycles"},
        counter_metadata {"Ray tracing triangle test misses", "rays"},
        counter_metadata {"Ray tracing non-opaque triangle hits", "tests"},
        counter_metadata {"Ray tracing opaque triangle hits", "tests"},
        counter_metadata {"Ray tracing started rays", "rays"},
        counter_metadata {"Average ray tracing unit cycles per thread", "cycles"},
        counter_metadata {"Ray tracing triangle node tests", "nodes"},
        counter_metadata {"Ray tracing triangle nodes with 1-4 rays", "nodes"},
        counter_metadata {"Ray tracing triangle nodes with 13-16 rays", "nodes"},
        counter_metadata {"Ray tracing triangle nodes with 5-8 rays", "nodes"},
        counter_metadata {"Ray tracing triangle nodes with 9-12 rays", "nodes"},
        counter_metadata {"Ray tracing triangle tester issue cycles", "cycles"},
        counter_metadata {"Ray tracing unit utilization", "percent"},
        counter_metadata {"Tiler vertex cache read stall cycles", "cycles"},
        counter_metadata {"Binning phase queue active cycles", "cycles"},
        counter_metadata {"Binning phase queue endpoint stall cycles", "cycles"},
        counter_metadata {"Binning phase queue interrupt pending cycles", "cycles"},
        counter_metadata {"Binning phase jobs", "jobs"},
        counter_metadata {"Binning phase tasks", "tasks"},
        counter_metadata {"Binning phase queue utilization", "percent"},
        counter_metadata {"Binning phase work queued cycles", "cycles"},
        counter_metadata {"Shader core compute or binning phase active cycles", "cycles"},
        counter_metadata {"Non-main phase core tasks", "tasks"},
        counter_metadata {"Shader core Compute or binning phase utilization", "percent"},
        counter_metadata {"Deferred vertex shading primitives", "primitives"},
        counter_metadata {"Deferred vertex shading primitive percentage", "percent"},
        counter_metadata {"Scissor test culled primitives", "primitives"},
        counter_metadata {"Scissor test cull percentage", "percent"},
        counter_metadata {"Shader core main phase active cycles", "cycles"},
        counter_metadata {"Main phase queue active cycles", "cycles"},
        counter_metadata {"Main phase queue endpoint stall cycles", "cycles"},
        counter_metadata {"Main phase queue interrupt pending cycles", "cycles"},
        counter_metadata {"Main phase jobs", "jobs"},
        counter_metadata {"Main phase tasks", "tasks"},
        counter_metadata {"Main phase queue utilization", "percent"},
        counter_metadata {"Main phase work queued cycles", "cycles"},
        counter_metadata {"Shader core main phase utilization", "percent"},
        counter_metadata {"Texture unit complex texture load cycles", "cycles"},
        counter_metadata {"Texture unit simple texture load cycles", "cycles"},
        counter_metadata {"Texture unit clock active cycles", "cycles"},
        counter_metadata {"Texture unit causing starvation cycles", "cycles"},
        counter_metadata {"Texture unit index calculation cycles", "cycles"},
        counter_metadata {"Texture unit L1 texture cache load cycles", "cycles"},
        counter_metadata {"Texture unit L1 texture cache lookup cycles", "cycles"},
        counter_metadata {"Texture unit L1 texture cache output cycles", "cycles"},
        counter_metadata {"Texture unit messages with single quad", "issues"},
        counter_metadata {"Tiler primitive assembly position shading stall cycles", "cycles"},
        counter_metadata {"Command stream 4 wait stall cycles", "cycles"},
        counter_metadata {"Command stream 5 wait stall cycles", "cycles"},
        counter_metadata {"Command stream doorbell interrupt pending cycles", "cycles"},
        counter_metadata {"Command stream 4 active cycles", "cycles"},
        counter_metadata {"Command stream 5 active cycles", "cycles"},
        counter_metadata {"Deferred vertex warps", "warps"},
        counter_metadata {"Attribute unit backpressure cycles", "cycles"},
        counter_metadata {"Attribute unit backpressure percentage", "percent"},
        counter_metadata {"Blend unit backpressure cycles", "cycles"},
        counter_metadata {"Blend unit backpressure percentage", "percent"},
        counter_metadata {"Load/store unit backpressure cycles", "cycles"},
        counter_metadata {"Load/store unit backpressure percentage", "percent"},
        counter_metadata {"Slot 0 arithmetic issue cycles", "cycles"},
        counter_metadata {"Slot 1 arithmetic issue cycles", "cycles"},
        counter_metadata {"Any slot arithmetic issue cycles", "cycles"},
        counter_metadata {"Texture unit backpressure cycles", "cycles"},
        counter_metadata {"Texture unit backpressure percentage", "percent"},
        counter_metadata {"Varying unit backpressure cycles", "cycles"},
        counter_metadata {"Varying unit backpressure percentage", "percent"},
        counter_metadata {"ZS unit backpressure cycles", "cycles"},
        counter_metadata {"ZS unit backpressure percentage", "percent"},
        counter_metadata {"Input fragment primitives", "primitives"},
        counter_metadata {"Fragment main pass stall cycles", "cycles"},
        counter_metadata {"Fragment main pass stall percentage", "percent"},
        counter_metadata {"Fragment main pass threads", "threads"},
        counter_metadata {"Fragment prepass culled primitives", "primitives"},
        counter_metadata {"Fragment prepass primitive culling percentage", "percent"},
        counter_metadata {"Fragment prepass early ZS updated quads", "quads"},
        counter_metadata {"Fragment prepass killed quads", "quads"},
        counter_metadata {"Fragment prepass killed quad percentage", "percent"},
        counter_metadata {"Fragment prepass primitives", "primitives"},
        counter_metadata {"Fragment prepass primitive percentage", "percent"},
        counter_metadata {"Fragment prepass skipped primitive percentage", "percent"},
        counter_metadata {"Fragment prepass skipped primitives", "primitives"},
        counter_metadata {"Fragment prepass tested quads", "quads"},
        counter_metadata {"Fragment prepass threads", "threads"},
        counter_metadata {"Fragment prepass warps", "warps"},
        counter_metadata {"Fragment prepass warp percentage", "percent"},
        counter_metadata {"Partial tiler position shading requests", "requests"},
        counter_metadata {"Partial tiler varying shading requests", "requests"},
        counter_metadata {"Attribute unit issue cycles", "cycles"},
        counter_metadata {"Attribute unit utilization", "percent"},
        counter_metadata {"Blend unit issue cycles", "cycles"},
        counter_metadata {"Blend unit utilization", "percent"},
        counter_metadata {"Neural accelerator clock ratio", "percent"},
        counter_metadata {"Ray tracing unit backpressure cycles", "cycles"},
        counter_metadata {"Ray tracing unit backpressure percentage", "percent"},
        counter_metadata {"Shader core instruction cache starvation cycles", "cycles"},
        counter_metadata {"Neural accelerator internal memory accesses", "bytes"},
        counter_metadata {"Neural accelerator active cycles", "cycles"},
        counter_metadata {"Neural accelerator convolution unit destination write bytes", "bytes"},
        counter_metadata {"Neural accelerator convolution unit source 0 read bytes", "bytes"},
        counter_metadata {"Neural accelerator convolution unit source 1 read bytes", "bytes"},
        counter_metadata {"Neural accelerator convolution unit source 2 read bytes", "bytes"},
        counter_metadata {"Neural accelerator port 1 read bytes from the L2 memory system", "bytes"},
        counter_metadata {"Neural accelerator input read unit destination write bytes", "bytes"},
        counter_metadata {"Neural accelerator input read unit read bytes from the L2 memory system", "bytes"},
        counter_metadata {"Neural accelerator input read unit source 0 read bytes", "bytes"},
        counter_metadata {"Neural accelerator port 0 read bytes from the L2 memory system", "bytes"},
        counter_metadata {"Neural accelerator output write unit write bytes to L2 memory system", "bytes"},
        counter_metadata {"Neural accelerator transform unit destination write bytes", "bytes"},
        counter_metadata {"Neural accelerator transform unit source 0 read bytes", "bytes"},
        counter_metadata {"Neural accelerator read bytes from the L2 memory system", "bytes"},
        counter_metadata {"Neural accelerator vector unit destination write bytes", "bytes"},
        counter_metadata {"Neural accelerator vector unit source 0 read bytes", "bytes"},
        counter_metadata {"Neural accelerator vector unit source 1 read bytes", "bytes"},
        counter_metadata {"Neural accelerator vector unit source 2 read bytes", "bytes"},
        counter_metadata {"Neural accelerator weight read unit destination write bytes", "bytes"},
        counter_metadata {"Neural accelerator weight read unit read bytes from the L2 memory system", "bytes"},
        counter_metadata {"Neural accelerator control unit processing cycles", "cycles"},
        counter_metadata {"Neural accelerator convolution unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator convolution unit blocks", "blocks"},
        counter_metadata {"Neural accelerator convolution unit utilization", "percent"},
        counter_metadata {"Neural accelerator convolution unit workload", "issues"},
        counter_metadata {"Neural accelerator DMA processing cycles", "cycles"},
        counter_metadata {"Neural accelerator descriptor fetch active cycles", "cycles"},
        counter_metadata {"Neural accelerator input read unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator input read unit blocks", "blocks"},
        counter_metadata {"Neural accelerator input read unit utilization", "percent"},
        counter_metadata {"Neural accelerator output write unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator output write unit blocks", "blocks"},
        counter_metadata {"Neural accelerator output write unit utilization", "percent"},
        counter_metadata {"Neural accelerator convolution unit 2D convolution cycles", "cycles"},
        counter_metadata {"Neural accelerator convolution unit depth-wise 2D convolution cycles", "cycles"},
        counter_metadata {"Neural accelerator convolution unit pooling cycles", "cycles"},
        counter_metadata {"Neural accelerator transform unit dimension change cycles", "cycles"},
        counter_metadata {"Neural accelerator transform unit element order cycles", "cycles"},
        counter_metadata {"Neural accelerator transform unit element replicate cycles", "cycles"},
        counter_metadata {"Neural accelerator transform unit element select cycles", "cycles"},
        counter_metadata {"Neural accelerator transform unit weight convert cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit block-wise reduction cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit element-wise binary cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit element-wise reduction cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit element-wise unary cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit post process cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit resize cycles", "cycles"},
        counter_metadata {"Neural accelerator data processing cycles", "cycles"},
        counter_metadata {"Neural accelerator data processing utilization", "percent"},
        counter_metadata {"Neural accelerator resource table fetch active cycles", "cycles"},
        counter_metadata {"Neural accelerator scheduler unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator scheduler unit utilization", "percent"},
        counter_metadata {"Neural accelerator transform unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator transform unit blocks", "blocks"},
        counter_metadata {"Neural accelerator transform unit processing cycles", "cycles"},
        counter_metadata {"Neural accelerator output transform unit utilization", "percent"},
        counter_metadata {"Neural accelerator input tasks", "tasks"},
        counter_metadata {"Neural accelerator output tasks", "tasks"},
        counter_metadata {"Neural accelerator vector unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator vector unit blocks", "blocks"},
        counter_metadata {"Neural accelerator vector unit utilization", "percent"},
        counter_metadata {"Neural accelerator vector unit workload", "issues"},
        counter_metadata {"Neural accelerator weight read unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator weight read unit blocks", "blocks"},
        counter_metadata {"Neural accelerator Weight read unit utilization", "percent"},
        counter_metadata {"Neural accelerator WF cumulative pipeline cycles", "issues"},
        counter_metadata {"Neural accelerator active in shader clock cycles", "cycles"},
        counter_metadata {"Neural queue active cycles", "cycles"},
        counter_metadata {"Neural queue endpoint stall cycles", "cycles"},
        counter_metadata {"Neural queue interrupt pending cycles", "cycles"},
        counter_metadata {"Neural jobs", "jobs"},
        counter_metadata {"Neural tasks", "tasks"},
        counter_metadata {"Neural queue utilization", "percent"},
        counter_metadata {"Neural work queued cycles", "cycles"},
        counter_metadata {"Neural accelerator utilization", "percent"},
        counter_metadata {"Ray tracing unit active cycles", "cycles"},
        counter_metadata {"Ray tracing culled BLAS instances", "issues"},
        counter_metadata {"Ray tracing BLAS instances", "issues"},
        counter_metadata {"Ray tracing box tests", "issues"},
        counter_metadata {"Ray tracing unit cache hits", "requests"},
        counter_metadata {"Ray tracing unit cache hit rate", "percent"},
        counter_metadata {"Ray tracing unit cache misses", "requests"},
        counter_metadata {"Ray tracing new trace messages", "requests"},
        counter_metadata {"Ray tracing culled primitives", "issues"},
        counter_metadata {"Ray tracing resume trace messages", "requests"},
        counter_metadata {"Ray tracing resumed rays", "rays"},
        counter_metadata {"Ray tracing deep traversals", "rays"},
        counter_metadata {"Ray tracing TLAS box tests", "issues"},
        counter_metadata {"Ray tracing triangle primitive tests", "issues"},
        counter_metadata {"Ray tracing unit read beats from external memory", "beats"},
        counter_metadata {"Ray tracing unit read bytes from external memory", "bytes"},
        counter_metadata {"Ray tracing unit read beats from L2 cache", "beats"},
        counter_metadata {"Ray tracing unit read bytes from L2 cache", "bytes"},
        counter_metadata {"Core cycles with 0-25% thread occupancy", "cycles"},
        counter_metadata {"Core cycles with 25-50% thread occupancy", "cycles"},
        counter_metadata {"Core cycles with 50-75% thread occupancy", "cycles"},
        counter_metadata {"Core cycles with 75-100% thread occupancy", "cycles"},
        counter_metadata {"Warps using 81-128 registers", "warps"},
        counter_metadata {"Warps using 0-32 registers", "warps"},
        counter_metadata {"Warps using 33-80 registers", "warps"},
        counter_metadata {"Total arithmetic issue slot 0 cycles", "cycles"},
        counter_metadata {"Total arithmetic issue slot 1 cycles", "cycles"},
        counter_metadata {"Neural accelerator motion unit destination 0 read bytes", "bytes"},
        counter_metadata {"Neural accelerator motion unit destination 0 write bytes", "bytes"},
        counter_metadata {"Neural accelerator motion unit destination 1 read bytes", "bytes"},
        counter_metadata {"Neural accelerator motion unit destination 1 write bytes", "bytes"},
        counter_metadata {"Neural accelerator motion unit source 0 read bytes", "bytes"},
        counter_metadata {"Neural accelerator motion unit source 1 read bytes", "bytes"},
        counter_metadata {"Neural accelerator motion unit workload", "tasks"},
        counter_metadata {"Neural accelerator motion unit active cycles", "cycles"},
        counter_metadata {"Neural accelerator motion unit utilization", "percent"},
        counter_metadata {"Neural accelerator motion unit blocks", "blocks"},
        counter_metadata {"Ray tracing box tests due to resumes", "issues"},
        counter_metadata {"Ray tracing micromap misses", "tests"},
        counter_metadata {"Ray tracing non-opaque opacity micromap hits", "tests"},
        counter_metadata {"Ray tracing opaque opacity micromap hits", "tests"},
        counter_metadata {"Ray tracing unit load/store cache write beats", "beats"}
    };

} // namespace database
} // namespace hwcpipe

