/*
 * Copyright (c) 2023 Arm Limited.
 *
 * SPDX-License-Identifier: MIT
 */

#include "hwcpipe/counter_metadata.hpp"

namespace hwcpipe {
namespace database {

constexpr std::array<counter_metadata, 203> all_counter_metadata{
    counter_metadata{"GPU active cycles", "cycles"},
    counter_metadata{"GPU interrupt pending cycles", "cycles"},
    counter_metadata{"Fragment tasks", "tasks"},
    counter_metadata{"Fragment queue active cycles", "cycles"},
    counter_metadata{"Non-fragment queue active cycles", "cycles"},
    counter_metadata{"Output external write beats", "beats"},
    counter_metadata{"Output external read beats", "beats"},
    counter_metadata{"Output external read stall cycles", "cycles"},
    counter_metadata{"Output external write stall cycles", "cycles"},
    counter_metadata{"Fragment active cycles", "cycles"},
    counter_metadata{"Fragment threads", "threads"},
    counter_metadata{"Fragment helper threads", "threads"},
    counter_metadata{"Rasterized fine quads", "quads"},
    counter_metadata{"Early ZS tested quads", "quads"},
    counter_metadata{"Early ZS killed quads", "quads"},
    counter_metadata{"Late ZS tested threads", "threads"},
    counter_metadata{"Late ZS tested threads", "threads"},
    counter_metadata{"Tiles", "tiles"},
    counter_metadata{"Unchanged tiles killed", "tiles"},
    counter_metadata{"Non-fragment active cycles", "cycles"},
    counter_metadata{"Non-fragment threads", "threads"},
    counter_metadata{"Execution core active cycles", "cycles"},
    counter_metadata{"Executed instructions", "instructions"},
    counter_metadata{"Load/store total issues", "cycles"},
    counter_metadata{"Texture instructions", "instructions"},
    counter_metadata{"Texture filtering cycles", "cycles"},
    counter_metadata{"Load/store read hits", "cycles"},
    counter_metadata{"Load/store write hits", "cycles"},
    counter_metadata{"Triangle primitives", "primitives"},
    counter_metadata{"Point primitives", "primitives"},
    counter_metadata{"Line primitives", "primitives"},
    counter_metadata{"Visible front-facing primitives", "primitives"},
    counter_metadata{"Visible back-facing primitives", "primitives"},
    counter_metadata{"Visible primitives", "primitives"},
    counter_metadata{"Facing and XY plane test culled primitives", "primitives"},
    counter_metadata{"Z plane culled primitives", "primitives"},
    counter_metadata{"Tiler active cycles", "cycles"},
    counter_metadata{"MMU lookup requests", "requests"},
    counter_metadata{"Any lookup requests", "requests"},
    counter_metadata{"Read lookup requests", "requests"},
    counter_metadata{"Write lookup requests", "requests"},
    counter_metadata{"Forward pixel kill buffer active cycles", "cycles"},
    counter_metadata{"Load/store read issues", "cycles"},
    counter_metadata{"Load/store write issues", "cycles"},
    counter_metadata{"Load/store atomic issues", "cycles"},
    counter_metadata{"Position cache hit requests", "requests"},
    counter_metadata{"Position cache miss requests", "requests"},
    counter_metadata{"Sample test culled primitives", "primitives"},
    counter_metadata{"Output internal read beats", "beats"},
    counter_metadata{"Internal write beats", "beats"},
    counter_metadata{"Tiler position shading requests", "requests"},
    counter_metadata{"Tiler position shading stall cycles", "cycles"},
    counter_metadata{"Tiler position FIFO full cycles", "cycles"},
    counter_metadata{"Varying cache hits", "requests"},
    counter_metadata{"Varying cache misses", "requests"},
    counter_metadata{"Tiler varying shading requests", "requests"},
    counter_metadata{"Tiler varying shading stall cycles", "cycles"},
    counter_metadata{"Rasterized primitives", "primitives"},
    counter_metadata{"Fragment warps", "warps"},
    counter_metadata{"Partial fragment warps", "warps"},
    counter_metadata{"Early ZS updated quads", "quads"},
    counter_metadata{"Late ZS tested quads", "quads"},
    counter_metadata{"Late ZS killed quads", "quads"},
    counter_metadata{"FPK occluder quads", "quads"},
    counter_metadata{"Non-fragment warps", "warps"},
    counter_metadata{"Diverged instructions", "instructions"},
    counter_metadata{"Execution engine starvation cycles", "cycles"},
    counter_metadata{"Texture quads", "quads"},
    counter_metadata{"Texture quad issues", "issues"},
    counter_metadata{"Texture quad descriptor misses", "requests"},
    counter_metadata{"Mipmapped texture quad issues", "issues"},
    counter_metadata{"Trilinear filtered texture quad issues", "issues"},
    counter_metadata{"Texture line fetch requests", "issues"},
    counter_metadata{"Compressed texture line fetch requests", "issues"},
    counter_metadata{"Texture cache lookup requests", "requests"},
    counter_metadata{"Load/store full read issues", "cycles"},
    counter_metadata{"Load/store partial read issues", "cycles"},
    counter_metadata{"Load/store full write issues", "cycles"},
    counter_metadata{"Load/store partial write issues", "cycles"},
    counter_metadata{"Varying instructions", "instructions"},
    counter_metadata{"32-bit interpolation slots", "issues"},
    counter_metadata{"16-bit interpolation slots", "issues"},
    counter_metadata{"Attribute instructions", "instructions"},
    counter_metadata{"Fragment front-end read beats from L2 cache", "beats"},
    counter_metadata{"Fragment front-end read beats from external memory", "beats"},
    counter_metadata{"Load/store read beats from L2 cache", "beats"},
    counter_metadata{"Load/store read beats from external memory", "beats"},
    counter_metadata{"Texture read beats from L2 cache", "beats"},
    counter_metadata{"Texture read beats from external memory", "beats"},
    counter_metadata{"Miscellaneous read beats from L2 cache", "beats"},
    counter_metadata{"Internal load/store write-back write beats", "beats"},
    counter_metadata{"Tile buffer write beats to L2 memory system", "beats"},
    counter_metadata{"Internal load/store other write beats", "beats"},
    counter_metadata{"Input internal read requests", "requests"},
    counter_metadata{"Input internal read stall cycles", "cycles"},
    counter_metadata{"Input internal write requests", "requests"},
    counter_metadata{"Input internal write stall cycles", "cycles"},
    counter_metadata{"Input internal snoop requests", "requests"},
    counter_metadata{"Input internal snoop stall cycles", "cycles"},
    counter_metadata{"Output internal read requests", "requests"},
    counter_metadata{"Output internal read stall cycles", "cycles"},
    counter_metadata{"Output internal write requests", "requests"},
    counter_metadata{"Input external snoop lookup requests", "requests"},
    counter_metadata{"Output external read transactions", "transactions"},
    counter_metadata{"Output external ReadNoSnoop transactions", "transactions"},
    counter_metadata{"Output external ReadUnique transactions", "transactions"},
    counter_metadata{"Output external outstanding reads 0-25%", "transactions"},
    counter_metadata{"Output external outstanding reads 25-50%", "transactions"},
    counter_metadata{"Output external outstanding reads 50-75%", "transactions"},
    counter_metadata{"Output external read latency 0-127 cycles", "beats"},
    counter_metadata{"Output external read latency 128-191 cycles", "beats"},
    counter_metadata{"Output external read latency 192-255 cycles", "beats"},
    counter_metadata{"Output external read latency 256-319 cycles", "beats"},
    counter_metadata{"Output external read latency 320-383 cycles", "beats"},
    counter_metadata{"Output external write transactions", "transactions"},
    counter_metadata{"Output external WriteNoSnoopFull transactions", "transactions"},
    counter_metadata{"Output external WriteNoSnoopPartial transactions", "transactions"},
    counter_metadata{"Output external WriteSnoopFull transactions", "transactions"},
    counter_metadata{"Output external WriteSnoopPartial transactions", "transactions"},
    counter_metadata{"Output external outstanding writes 0-25%", "transactions"},
    counter_metadata{"Output external outstanding writes 25-50%", "transactions"},
    counter_metadata{"Output external outstanding writes 50-75%", "transactions"},
    counter_metadata{"Input external snoop transactions", "transactions"},
    counter_metadata{"Input external snoop stall cycles", "cycles"},
    counter_metadata{"Warps using more than 32 registers", "warps"},
    counter_metadata{"Full quad warps", "warps"},
    counter_metadata{"Mipmapped texture instructions", "instructions"},
    counter_metadata{"Compressed texture instructions", "instructions"},
    counter_metadata{"3D texture instructions", "instructions"},
    counter_metadata{"Trilinear filtered texture instructions", "instructions"},
    counter_metadata{"Texture filtering coordinate stall cycles", "cycles"},
    counter_metadata{"Texture line fill stall cycles", "cycles"},
    counter_metadata{"Texture filtering partial data stall cycles", "cycles"},
    counter_metadata{"Load/store write beats to L2 memory system", "beats"},
    counter_metadata{"Miscellaneous write beats to L2 memory system", "beats"},
    counter_metadata{"Partial rasterized fine quads", "quads"},
    counter_metadata{"Arithmetic FMA instructions", "instructions"},
    counter_metadata{"Arithmetic CVT instructions", "instructions"},
    counter_metadata{"Arithmetic SFU instructions", "instructions"},
    counter_metadata{"Instruction cache misses", "requests"},
    counter_metadata{"Blend shader instructions", "instructions"},
    counter_metadata{"Texture message read beats", "beats"},
    counter_metadata{"Texture descriptor stalls", "cycles"},
    counter_metadata{"Texture fetch stalls", "cycles"},
    counter_metadata{"Texture filtering stalls", "cycles"},
    counter_metadata{"Texture filtering cycles using 4x bilinear", "cycles"},
    counter_metadata{"Texture filtering cycles using 2x trilinear", "cycles"},
    counter_metadata{"Texture messages", "issues"},
    counter_metadata{"Texture message write beats", "beats"},
    counter_metadata{"Any active cycles", "cycles"},
    counter_metadata{"MCU active cycles", "cycles"},
    counter_metadata{"Any iterator active cycles", "cycles"},
    counter_metadata{"Vertex iterator queued", "cycles"},
    counter_metadata{"Vertex endpoint stall cycles", "cycles"},
    counter_metadata{"Compute iterator queued", "cycles"},
    counter_metadata{"Compute endpoint stall cycles", "cycles"},
    counter_metadata{"Fragment iterator queued", "cycles"},
    counter_metadata{"Fragment endpoint stall cycles", "cycles"},
    counter_metadata{"Command execution unit active", "cycles"},
    counter_metadata{"Command load/store unit active", "cycles"},
    counter_metadata{"Command stream 0 active", "cycles"},
    counter_metadata{"Command stream 1 active", "cycles"},
    counter_metadata{"Command stream 2 active", "cycles"},
    counter_metadata{"Command stream 3 active", "cycles"},
    counter_metadata{"Input internal evict requests", "requests"},
    counter_metadata{"Input internal clean unique requests", "requests"},
    counter_metadata{"Narrow arithmetic instructions", "instructions"},
    counter_metadata{"Rasterized coarse quads", "quads"},
    counter_metadata{"Ray tracing triangle batches tested", "batches"},
    counter_metadata{"Ray tracing box nodes tested", "boxes"},
    counter_metadata{"Ray tracing triangle batches tested with 1-4 rays", "batches"},
    counter_metadata{"Ray tracing triangle batches tested with 5-8 rays", "batches"},
    counter_metadata{"Ray tracing triangle batches tested with 9-12 rays", "batches"},
    counter_metadata{"Ray tracing triangle batches tested with 13-16 rays", "batches"},
    counter_metadata{"Ray tracing box nodes tested with 1-4 rays", "nodes"},
    counter_metadata{"Ray tracing box nodes tested with 5-8 rays", "nodes"},
    counter_metadata{"Ray tracing box nodes tested with 9-12 rays", "nodes"},
    counter_metadata{"Ray tracing box nodes tested with 13-16 rays", "nodes"},
    counter_metadata{"Ray tracing opaque triangle hits", "tests"},
    counter_metadata{"Ray tracing non-opaque triangle hits", "tests"},
    counter_metadata{"Ray tracing first hit terminations", "rays"},
    counter_metadata{"Ray tracing miss", "rays"},
    counter_metadata{"Ray tracing rays started", "rays"},
    counter_metadata{"Ray tracing box tester issue cycles", "issues"},
    counter_metadata{"Ray tracing triangle tester issue cycles", "issues"},
    counter_metadata{"Facing test culled primitives", "primitives"},
    counter_metadata{"Frustum test culled primitives", "primitives"},
    counter_metadata{"Binning phase iterator queued", "cycles"},
    counter_metadata{"Binning phase endpoint stall cycles", "cycles"},
    counter_metadata{"Main phase iterator queued", "cycles"},
    counter_metadata{"Main phase endpoint stall cycles", "cycles"},
    counter_metadata{"L1 texture cache load cycles", "cycles"},
    counter_metadata{"Simple texture load cycles", "cycles"},
    counter_metadata{"L1 texture cache output cycles", "cycles"},
    counter_metadata{"L1 texture cache lookup cycles", "cycles"},
    counter_metadata{"Texture messages with single quad", "issues"},
    counter_metadata{"Texture cache lookup cycles", "cycles"},
    counter_metadata{"Complex texture load cycles", "cycles"},
    counter_metadata{"Texture index calculation cycles", "cycles"},
    counter_metadata{"Texture causing starvation cycles", "cycles"},
    counter_metadata{"Texture active cycles", "cycles"},
    counter_metadata{"Scissor test culled primitives", "primitives"},
    counter_metadata{"Visible primitives using DVS", "primitives"}};

} // namespace database
} // namespace hwcpipe
