name: Build for Android with Clang using the NDK

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Download and set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
        unzip android-ndk-r27-linux.zip
        echo "export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r27" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux/bin:$PATH" >> $GITHUB_ENV

    - name: Build with Clang and Android NDK
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 ..
        make
